---
title: "hw6"
author: "Kate"
date: "2025-12-03"
output:  github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(broom)
library(modelr)
library(p8105.datasets)
library(forcats)

set.seed(1)
theme_set(theme_minimal(base_size = 14))
```

## Problem 1

```{r, warning = FALSE}
# Import homicide data from Washington Post GitHub
homicide_raw <- read_csv(
  "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"
)

# indicator identification and split data
homicide_clean <- homicide_raw %>%
  mutate(
    city_state = str_c(city, ", ", state),
    solved = disposition == "Closed by arrest"
  )%>%
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", 
                      "Kansas City, MO", "Tulsa, AL")
  ) %>%
  filter(victim_race %in% c("White", "Black")) %>%
  mutate(
    victim_age = as.numeric(victim_age),
    victim_sex = factor(victim_sex),
    victim_race = factor(victim_race)
  )

```

### Logistic Regression for one city
```{r}
logistic_df <- homicide_clean %>%
  filter(city_state == "Baltimore, MD")

logistic_fit <- glm(
  solved ~ victim_age + victim_sex + victim_race,
  data = logistic_df,
  family = binomial()
)

logistic_OR <- logistic_fit %>%
  tidy(conf.int = TRUE, exponentiate = TRUE) %>%
  filter(term == "victim_sexMale") %>%
  select(term, estimate, conf.low, conf.high)

logistic_OR
```

### Logistic Regression for Each City 
```{r}
city_ORs <- homicide_clean %>%
  group_by(city_state) %>%
  nest() %>%
  mutate(
    fit = map(
      data,
      ~ glm(solved ~ victim_age + victim_sex + victim_race,
            data = .x,
            family = binomial())
    ),
    tidied = map(
      fit,
      ~ tidy(.x, conf.int = TRUE, exponentiate = TRUE)
    )
  ) %>%
  unnest(tidied) %>%
  filter(term == "victim_sexMale") %>%
  select(city_state, estimate, conf.low, conf.high)

city_ORs
```
### plot for each city
```{r}


city_ORs_plotdata <- city_ORs 

ggplot(city_ORs_plotdata,
aes(x = fct_reorder(city_state,estimate,.desc = TRUE), y = estimate,
ymin = conf.low, ymax = conf.high)) +
geom_pointrange() +
geom_hline(yintercept = 1, linetype = "dashed") +
coord_flip() +
labs(
x = "City",
y = "Odds ratio (Male vs Female victims)",
title = "Estimated odds ratios of homicide case being solved,\nby victim sex and city",
subtitle = "Points = OR estimates; bars = 95% confidence intervals; dashed line = OR = 1"
) +
theme(
    axis.text.y = element_text(size = 6)
)
```
